backend:
  name: github
  repo: chrispaynaganan/portfolio
  branch: main
  base_url: https://cms-oauth3.vercel.app

media_folder: src/assets/images
public_folder: /src/assets/images

local_backend: false

collections:
  - name: faqs
    label: FAQs
    files:
      - label: FAQs
        name: faqs
        file: src/data/faqs.json
        fields:
          - label: FAQs
            name: faqs
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: text }

  - name: services
    label: Services
    files:
      - label: Services
        name: services
        file: src/data/services.json
        fields:
          - label: Services
            name: services
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: Icon, name: icon, widget: string, required: false }
          - label: Packages
            name: packages
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Name, name: name, widget: string }
              - { label: Price, name: price, widget: string }
              - { label: Description, name: description, widget: text }
              - label: Features
                name: features
                widget: list
                field: { label: Feature, name: feature, widget: string }

  - name: nav
    label: Navigation
    files:
      - label: Nav Links
        name: nav
        file: src/data/nav.json
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Path, name: path, widget: string }